export const ALL_SERVICES = [
  "Alongamento de unhas",
  "Aplicação / manutenção de cílios",
  "Barba masculina",
  "Body piercing",
  "Botox facial",
  "Bronzeamento artificial",
  "Cabelos afros",
  "Corte feminino",
  "Corte masculino",
  "Depilação à laser",
  "Depilação corporal",
  "Depilação facial",
  "Esmaltação em gel",
  "Limpeza de pele",
  "Manicure / pedicure tradicional",
  "Maquiagem",
  "Massagem corporal",
  "Mega Hair",
  "Nanoblanding",
  "Penteados",
  "Podologia",
  "Progressiva / alisamento definitivo",
  "Trancista",
  "Tratamento capilar",
  "Tratamento facial",
];
